# Generated by Django 6.0.6 on 2026-07-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='file_key',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
