# Generated by Django 6.0.6 on 2026-06-17 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
        ('core', '0001_initial'),
        ('live', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomsession',
            name='live_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_sessions', to='live.livesession'),
        ),
        migrations.AddField(
            model_name='classroomsession',
            name='remote_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remote_classroom_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.organization'),
        ),
        migrations.AddField(
            model_name='room',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.organization'),
        ),
        migrations.AddField(
            model_name='containerclassroom',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='container', to='classrooms.room'),
        ),
        migrations.AddField(
            model_name='classroomsession',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='classrooms.room'),
        ),
        migrations.AddField(
            model_name='seat',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='classrooms.room'),
        ),
        migrations.AddField(
            model_name='seatattendance',
            name='classroom_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_attendance', to='classrooms.classroomsession'),
        ),
        migrations.AddField(
            model_name='seatattendance',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='classrooms.seat'),
        ),
        migrations.AddField(
            model_name='seatattendance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seatdevicemapping',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_mappings', to='classrooms.device'),
        ),
        migrations.AddField(
            model_name='seatdevicemapping',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_mappings', to='classrooms.seat'),
        ),
        migrations.AddField(
            model_name='smartevent',
            name='classroom_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='classrooms.classroomsession'),
        ),
        migrations.AddField(
            model_name='smartevent',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='classrooms.seat'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('room', 'label'), name='unique_room_seat'),
        ),
    ]
