# Generated by Django 6.0.6 on 2026-06-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(max_length=40, unique=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=40)),
                ('total_hours', models.PositiveIntegerField(default=0)),
                ('pdf_url', models.URLField(blank=True)),
                ('verification_code', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('revoked', 'Revoked')], default='issued', max_length=20)),
            ],
            options={
                'ordering': ['-issued_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('design', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
