# Generated by Django 6.0.6 on 2026-06-17 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('live', '0001_initial'),
        ('recordings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='recording',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='recordings.recording'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='live.livesession'),
        ),
        migrations.AddField(
            model_name='sessiondoubt',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubts', to='live.livesession'),
        ),
        migrations.AddField(
            model_name='sessiondoubt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_doubts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionregistration',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='live.livesession'),
        ),
        migrations.AddField(
            model_name='sessionregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traineravailability',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='sessionregistration',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='unique_session_registration'),
        ),
    ]
